apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: mariadb-operator-crds
    repoURL: https://helm.mariadb.com/mariadb-operator
    targetRevision: 26.3.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mariadb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
